[package]
edition = "2021"
name = "lo_"
version = "0.1.1"
authors = ["Saddam H <thedevsaddam@gmail.com>"]
description = "A modern Rust utility library delivering modularity, performance & extras proted from JavaScript Lodash"
readme = "README.md"
repository = "https://github.com/thedevsaddam/lo_"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
